apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: k8s-workshop
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081