apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workshop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-workshop
  template:
    metadata:
      labels:
        app: k8s-workshop
    spec:
      containers:
      - name: k8s-workshop
        imagePullPolicy: Never
        image: k8sworkshop:latest
        ports:
        - containerPort: 8081
